/**
 * The rules of the plugins that only apply to non-code files, by plugin, in
 * the order each plugin declares them. `true` marks a rule with a fixer.
 *
 * The linter plans from this list and loads a plugin the first time one of
 * its rules runs (see lazy.ts), so linting TypeScript never loads the
 * Markdown, shell or package.json rules. Kept in step with the plugins by
 * test/plugin/lazy-plugins.test.ts.
 */
export const LAZY_PLUGIN_RULES: Record<'markdown' | 'shell' | 'spell' | 'lockfile' | 'publint', Record<string, boolean>> = {
  markdown: {
    'heading-increment': true,
    'heading-style': true,
    'no-missing-space-atx': true,
    'no-multiple-space-atx': true,
    'no-missing-space-closed-atx': false,
    'no-multiple-space-closed-atx': false,
    'blanks-around-headings': true,
    'heading-start-left': true,
    'no-duplicate-heading': false,
    'single-title': true,
    'no-trailing-punctuation': true,
    'ul-style': true,
    'list-indent': false,
    'ul-indent': false,
    'ol-prefix': true,
    'list-marker-space': true,
    'blanks-around-lists': true,
    'no-trailing-spaces': true,
    'no-hard-tabs': true,
    'no-multiple-blanks': true,
    'no-multiple-space-blockquote': true,
    'no-blanks-blockquote': true,
    'blanks-around-fences': true,
    'single-trailing-newline': true,
    'blanks-around-tables': true,
    'no-reversed-links': false,
    'no-bare-urls': true,
    'no-space-in-links': false,
    'no-empty-links': false,
    'link-fragments': false,
    'reference-links-images': false,
    'link-image-reference-definitions': true,
    'link-image-style': true,
    'descriptive-link-text': false,
    'line-length': false,
    'commands-show-output': false,
    'fenced-code-language': false,
    'code-block-style': false,
    'code-fence-style': true,
    'no-emphasis-as-heading': true,
    'no-space-in-emphasis': true,
    'no-space-in-code': true,
    'emphasis-style': true,
    'strong-style': true,
    'no-inline-html': false,
    'hr-style': false,
    'first-line-heading': false,
    'required-headings': false,
    'proper-names': false,
    'no-alt-text': false,
    'table-pipe-style': false,
    'table-column-count': false,
    'table-column-style': false,
  },
  shell: {
    'command-substitution': true,
    'quote-variables': false,
    'no-cd-without-check': false,
    'no-eval': false,
    'no-useless-cat': false,
    'no-ls-parsing': false,
    'no-variable-in-single-quotes': false,
    'no-exit-in-subshell': false,
    'shebang': false,
    'indent': true,
    'function-style': true,
    'operator-spacing': true,
    'keyword-spacing': false,
    'no-trailing-semicolons': true,
    'no-trailing-whitespace': true,
    'prefer-double-brackets': true,
    'set-options': false,
    'prefer-printf': false,
    'consistent-case-terminators': false,
    'no-broken-redirect': false,
    'heredoc-indent': false,
  },
  spell: {
    'check': false,
    'check-comments': false,
    'check-markdown': false,
  },
  lockfile: {
    'validate-host': false,
    'validate-https': false,
    'validate-integrity': false,
    'validate-package-names': false,
    'validate-scheme': false,
  },
  publint: {
    'use-type': false,
    'local-dependency': false,
    'deprecated-field-jsnext': false,
    'has-module-but-no-exports': false,
    'field-invalid-value-type': false,
    'exports-types-should-be-first': false,
    'exports-default-should-be-last': false,
    'exports-module-should-precede-require': false,
    'exports-value-invalid': false,
    'exports-missing-root-entrypoint': false,
    'exports-fallback-array-use': false,
    'imports-key-invalid': false,
    'imports-value-invalid': false,
    'imports-default-should-be-last': false,
    'imports-module-should-precede-require': false,
    'file-does-not-exist': false,
    'file-invalid-format': false,
    'module-should-be-esm': false,
    'bin-file-not-executable': false,
    'exports-module-should-be-esm': false,
  },
}
